server:
  port: 9000
  servlet:
    context-path: /kafkaDemo
spring:
  application:
    name: kafkaDemo
  redis:
    # redis默认情况下有16个分片，这里配置具体使用的分片，默认为0
    database: 0
    host: 127.0.0.1
    port: 6379
    #password: root
    lettuce:
      pool:
        # 连接池最大连接数(使用负数表示没有限制),默认8
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0