mybatis:
  ## 开启mybatis 的二级缓存 针对mapper级别 namespacse
  configuration:
    cache-enabled: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/admin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
